-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 15:52:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Database market
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `market` DEFAULT CHARACTER SET utf8 ;
USE `market` ;

-- -----------------------------------------------------
-- Table `market`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `market`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `id_role` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(30) NOT NULL UNIQUE,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `roles` (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `id_category` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id_product`),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`id_category`)
    REFERENCES `categories` (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  PRIMARY KEY (`id_sale`),
  CONSTRAINT `fk_sales_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carts` (
  `id_sale` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id_sale`, `id_product`),
  CONSTRAINT `fk_carts_sales`
    FOREIGN KEY (`id_sale`)
    REFERENCES `sales` (`id_sale`),
  CONSTRAINT `fk_carts_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `products` (`id_product`))
ENGINE = InnoDB;
